#cloud-config
hostname: nomad-client-${count.index + 1}
fqdn: nomad-client-${count.index + 1}.local
package_update: true
package_upgrade: true
packages:
  - unzip
  - vim
  - net-tools

users:
  - name: laurelio
    gecos: Laurelio User
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,admin,docker
    lock_passwd: false
    passwd: "$6$r5rJoOafbORx0WXV$uAPDsus7vZRL1aI6b1ZNJdf5qhVuy.vy8IPKAbdxHy1ap3VqaWdGpebch6sEkEik4WsAoEBPvbDlpsoQ7AabB0"
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDwKPjcdnk1I4g0ehjIGjl7aKvp826Z8RN1pPiLd+BqFN443P1ldP6tN3SpKk3K2rwU506Mi6bwC4d0rhyg9kAFkd1RV9oriy+L9ASrvTZETtxBtT3ZybZnIM9oFuVlp234z7FvM0OCWI5M7pX2CvB9GJdIlNFSZRfuU14m7m/R5DcKMzNS3jnmOF7C5+BH5YZDUY8X8wKlAbakpNz4DjvU1L1j9Zpft74Z0JdgkhHH0wPaRjgtF12iQB6Ht4WT4HQnQl2x+oRLm0AV9ri9R7OTC/QGbt8E3YlFQo0K6WYfnKIOMCKd1i3qLlob9D5poyWRoEz3fIm25NCydgmPCj8OJ5SuuHXxP8JkP9SME63MfswKqdTwK1XV2w8qK7MVMKMV/v4iLOxtN/8Kmi21ubTzIiY0nSHuHLPUvSF3kwhRPX1Vrenuo++Xt34EK3suhtGXg5nW13SanGb4MK1u+cENs/vnPN56o3bBoBOpaOkGz6qb5pK2hSalKF5B+2/IvVs= laurelio@localhost.localdomain"

ssh_pwauth: true
disable_root: false

write_files:
  - path: /etc/consul.d/consul.hcl
    content: |
      datacenter = "dc1"
      data_dir = "/opt/consul"
      node_name = "consul-client-${count.index + 1}"
      server = false
      ui = true
      bind_addr = "10.0.0.1${count.index + 3}"
      client_addr = "0.0.0.0"
      retry_join = ["10.0.0.10", "10.0.0.11", "10.0.0.12"]
      ports { grpc = 8502 }
      connect { enabled = true }
      acl {
        enabled = true
        default_policy = "allow"
        enable_token_persistence = true
      }

# Store a public key in a file
  # - name: Store public key
  #   copy:
  #     content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDwKPjcdnk1I4g0ehjIGjl7aKvp826Z8RN1pPiLd+BqFN443P1ldP6tN3SpKk3K2rwU506Mi6bwC4d0rhyg9kAFkd1RV9oriy+L9ASrvTZETtxBtT3ZybZnIM9oFuVlp234z7FvM0OCWI5M7pX2CvB9GJdIlNFSZRfuU14m7m/R5DcKMzNS3jnmOF7C5+BH5YZDUY8X8wKlAbakpNz4DjvU1L1j9Zpft74Z0JdgkhHH0wPaRjgtF12iQB6Ht4WT4HQnQl2x+oRLm0AV9ri9R7OTC/QGbt8E3YlFQo0K6WYfnKIOMCKd1i3qLlob9D5poyWRoEz3fIm25NCydgmPCj8OJ5SuuHXxP8JkP9SME63MfswKqdTwK1XV2w8qK7MVMKMV/v4iLOxtN/8Kmi21ubTzIiY0nSHuHLPUvSF3kwhRPX1Vrenuo++Xt34EK3suhtGXg5nW13SanGb4MK1u+cENs/vnPN56o3bBoBOpaOkGz6qb5pK2hSalKF5B+2/IvVs= laurelio@localhost.localdomain"
  #     dest: /home/nomad/.ssh/id_rsa.pub

runcmd:
  - |
    for i in {1..10}; do
      IP=$(hostname -I | awk '{print $1}')
      if [[ ! -z "$IP" ]]; then
        LAST_OCTET=$(echo $IP | awk -F. '{print $4}')
        sudo hostnamectl set-hostname "nomad-client-${LAST_OCTET}"
        break
      fi
      sleep 2
    done
  
  - |
    if ! command -v curl &> /dev/null; then
      echo "curl is not installed. Installing required packages..."
      sudo yum install -y curl unzip vim jq docker docker-compose net-tools || echo "Failed to install packages"
    fi

  - sudo dnf install -y docker || echo "Failed to install Docker"
  - echo "nameserver 8.8.8.8" > /etc/resolv.conf
  - echo "nameserver 1.1.1.1" >> /etc/resolv.conf
  - curl -fsSL https://tailscale.com/install.sh | sh
  - systemctl enable --now tailscaled
  - tailscale up --authkey ${tailscale_auth_key} --reset
  - curl -fsSL https://releases.hashicorp.com/nomad/1.9.4/nomad_1.9.4_linux_amd64.zip -o nomad.zip || echo "Failed to download Nomad"
  - unzip nomad.zip -d /usr/local/bin/
  - chmod +x /usr/local/bin/nomad
  - rm nomad.zip
  - mkdir -p /etc/nomad.d /var/lib/nomad
  - curl -fsSL https://releases.hashicorp.com/consul/1.15.0/consul_1.15.0_linux_amd64.zip -o consul.zip || echo "Failed to download Consul"
  - unzip consul.zip -d /usr/local/bin/
  - chmod +x /usr/local/bin/consul
  - rm consul.zip
  - mkdir -p /etc/consul.d /var/lib/consul
  - systemctl enable --now docker
  - systemctl enable --now consul
  - systemctl enable --now nomad
  - ufw allow 22/tcp
  - ufw allow 8300:8302/tcp
  - ufw allow 8301:8302/udp
  - ufw allow 8500/tcp
  - ufw allow 8600/tcp
  - ufw allow 8600/udp
  - ufw allow 4646:4648/tcp
  - ufw allow 4648/udp
  - ufw --force enable

#   - |
#     for i in {1..10}; do
#       IP=$(hostname -I | awk '{print $1}')
#       if [[ ! -z "$IP" ]]; then
#         LAST_OCTET=$(echo $IP | awk -F. '{print $4}')
#         sudo hostnamectl set-hostname "nomad-client-${LAST_OCTET}"

#         # Create Nomad configuration file
#         sudo mkdir -p /etc/nomad.d
#         cat <<EOF | sudo tee /etc/nomad.d/nomad.hcl
#         data_dir  = "/opt/nomad"
#         bind_addr = "0.0.0.0"

#         client {
#           enabled = true
#           servers = ["10.0.0.10:4647", "10.0.0.11:4647", "10.0.0.12:4647"]
#         }

#         advertise {
#           http = "${IP}:4646"
#           rpc  = "${IP}:4647"
#           serf = "${IP}:4648"
#         }

#         node_name = "nomad-client-${LAST_OCTET}"
# EOF
#         break
#       fi
#       sleep 2
#     done  